language: c
sudo: false
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
 # - wget http://downloads.arduino.cc/arduino-1.6.5-linux64.tar.xz
  - wget http://downloads.arduino.cc/arduino-1.8.4-linux64.tar.xz
 # - tar xf arduino-1.6.5-linux64.tar.xz
  - tar xf arduino-1.8.4-linux64.tar.xz 
  - mv arduino-1.8.4-linux64 $HOME/arduino_ide
  - export PATH="$HOME/arduino_ide:$PATH"
 # - rm -rf $HOME/Arduino/libraries/*.pde
 # - rm -rf $HOME/Arduino/libraries/*.ino
 #- source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
install:
  - arduino --install-library "MySensors,Bounce2"
  - git clone https://github.com/JChristensen/DS3232RTC.git 
  - ln -s $PWD/DS3232RTC $HOME/Arduino/libraries/DS3232RTC
  - git clone https://github.com/marcmerlin/NewLiquidCrystal.git
  - ln -s $PWD/NewLiquidCrystal $HOME/Arduino/libraries/NewLiquidCrystal
  - ls -al $HOME/Arduino/libraries/  
script:
  - arduino --verify --board arduino:avr:uno $PWD/nazmang/RelayPowermeter/RelayPowermeter.ino
notifications:
  email:
    on_success: change
    on_failure: change