language: cpp
cache:
  directories:
    - $HOME/arduino_ide
sudo: false
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.8.4-linux64.tar.xz
  - tar xf arduino-1.8.4-linux64.tar.xz 
  - mv arduino-1.8.4 $HOME/arduino_ide
  - export PATH="$HOME/arduino_ide:$PATH"
install:
  - mkdir -p $HOME/Arduino/libraries
  - git clone https://github.com/JChristensen/DS3232RTC.git 
  - ln -s $PWD/DS3232RTC $HOME/Arduino/libraries/DS3232RTC
  - git clone https://github.com/mysensors/MySensorsArduinoExamples.git
  - ln -s $PWD/MySensorsArduinoExamples/libraries/LiquidCrystal $HOME/arduino_ide/LiquidCrystal
  - $HOME/arduino_ide/arduino --install-library "MySensors,Bounce2,Time"
  - $HOME/arduino_ide/arduino --install-boards "arduino:avr"
script:
  - $HOME/arduino_ide/arduino-builder -verbose  -hardware $HOME/arduino_ide/hardware -tools $HOME/arduino_ide/hardware/tools -tools $HOME/arduino_ide/tools-builder/ -fqbn arduino:avr:uno -libraries $HOME/arduino_ide $PWD/*.ino
notifications:
  email:
    on_success: change
    on_failure: change  