language: cpp
sudo: false
cache:
  directories:
    - $ARDUINO_PATH
    - $ARDUINO_PATH/arduino-$ARDUINO_VERSION
env:
  - ARDUINO_VERSION=1.8.4 ARDUINO_PATH=$HOME/arduino_ide ARDUINO_LIBS_PATH=$HOME/Arduino/libraries
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - if ! [[ -f $ARDUINO_PATH/arduino || -f $ARDUINO_PATH/arduino-$ARDUINO_VERSION/arduino ]]; then wget http://downloads.arduino.cc/arduino-1.8.4-linux64.tar.xz && tar xf arduino-1.8.4-linux64.tar.xz && cp -a  arduino-1.8.4 $ARDUINO_PATH; fi
  - if [ -d $ARDUINO_PATH/arduino-$ARDUINO_VERSION ]; then export ARDUINO_PATH=$ARDUINO_PATH/arduino-$ARDUINO_VERSION; fi
  - export PATH="$HOME/arduino_ide:$PATH"
  - export PATH="$HOME/arduino_ide/arduino-$ARDUINO_VERSION:$PATH"
install:
  - mkdir -p $ARDUINO_LIBS_PATH && mkdir -p $PWD/build
  - git clone https://github.com/JChristensen/DS3232RTC.git 
  - ln -s $PWD/DS3232RTC $ARDUINO_LIBS_PATH/DS3232RTC
  - git clone https://github.com/mysensors/MySensorsArduinoExamples.git
  - ln -s $PWD/MySensorsArduinoExamples/libraries/LiquidCrystal $ARDUINO_LIBS_PATH/LiquidCrystal
  - arduino --install-library "MySensors,Bounce2,Time"
  - arduino --install-boards "arduino:avr"
script:
  - arduino-builder -hardware $ARDUINO_PATH/hardware -tools $ARDUINO_PATH/hardware/tools -tools $ARDUINO_PATH/tools-builder -fqbn arduino:avr:uno -libraries $ARDUINO_LIBS_PATH -build-path $PWD/build $PWD/*.ino
notifications:
  email:
    on_success: change
    on_failure: change
before_deploy:
  - ls -lLa $PWD/build
deploy:
  provider: releases
  api_key:
    secure: JpHfz0ZCoLemvl9P9uJzk3Lx4YRAGiU5pW/LthdtbvOnlV4c8+UkNIF7cjGDHqxCTtsN9cujwFZVmejZyVCMvzm6hEN/0o9XDk4KsNzQaXOk/qElU2oCqbFFQCRIJ7B4OwKwsgRlJGZyv7msAzVco6jjokUPvy76uuYm+zb5q3BvP3I2mXkQKXWsee/hYt2Pxwyu8rGIvV2iskYjn080Jm+jGFour6rErf5I9WmY/8setUz0g4RuvSCqWDvx/8Sp6bo1jECPu7KrzsN7PVbFpJjzeIIRHoldV2uC8pjSvZOde05Eun8scRzC8xlAUC9h/sd2I3V63Dw5HnS+M3BAibeOujQG9JpJLocPGYksyw9exZTc7e8b8KMmSQiYYVBWhN+1OEM5ZJxJmi2RAqz0Si/0OTeDuSJWFbVei5ScCe+9z1CBM+r4vXyMPTtioiEzKJKVWYlfbhoqfM6pv9a9dE6dnE4CMnPFVAooO32aPCzAHNOZyYXzgLe0FKlyi1RvRB3trHoB72mJcE82AjEvbcudiPeHR85mKekmm7Mppu2BXkS/kBUN15sJGzqWmPJ99pmnfQCbZ6y5z9FEI9ref34445SBAPXxmlGw1GUGgQORIPnOyDNjsbDhGfiOTsGBOzdqoAAGGcmpdgTg2qSKWvytDShFJ4jyHg0NrLB6h80=
  file: "$PWD/build/RelayPowermeter.ino.hex"
  on:
    repo: nazmang/RelayPowermeter