language: c
sudo: false
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
install:
  - arduino --install-library "Time,SPI,DS3232RTC,MySensors,Bounce2,Wire LiquidCrystal_I2C"
script:
  - build_main_platforms
notifications:
  email:
    on_success: change
    on_failure: change