language: cpp
sudo: false
cache:
  directories:
    - $ARDUINO_PATH
    - $ARDUINO_PATH/arduino-$ARDUINO_VERSION
env:
  - ARDUINO_VERSION=1.8.4 ARDUINO_PATH=$HOME/arduino_ide ARDUINO_LIBS_PATH=$HOME/Arduino/libraries
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - if ! [[ -f $ARDUINO_PATH/arduino || -f $ARDUINO_PATH/arduino-$ARDUINO_VERSION ]]; then wget http://downloads.arduino.cc/arduino-1.8.4-linux64.tar.xz && tar xf arduino-1.8.4-linux64.tar.xz && cp -a  arduino-1.8.4 $ARDUINO_PATH; fi
  - export PATH="$HOME/arduino_ide:$PATH"
  - export PATH="$HOME/arduino_ide/arduino-$ARDUINO_VERSION:$PATH"
install:
  - mkdir -p $ARDUINO_LIBS_PATH
  - git clone https://github.com/JChristensen/DS3232RTC.git 
  - ln -s $PWD/DS3232RTC $ARDUINO_LIBS_PATH/DS3232RTC
  - git clone https://github.com/mysensors/MySensorsArduinoExamples.git
  - ln -s $PWD/MySensorsArduinoExamples/libraries/LiquidCrystal $ARDUINO_LIBS_PATH/LiquidCrystal
  - ls -al $HOME
  - ls -alL $ARDUINO_PATH
  - ls -alL $HOME/Arduino/libraries
  - arduino --install-library "MySensors,Bounce2,Time"
  - arduino --install-boards "arduino:avr"
script:
  - arduino-builder -verbose  -hardware $ARDUINO_PATH/hardware -tools $ARDUINO_PATH/hardware/tools -tools $ARDUINO_PATH/tools-builder -fqbn arduino:avr:uno -libraries $ARDUINO_LIBS_PATH -build-path $PWD $PWD/*.ino
notifications:
  email:
    on_success: change
    on_failure: change  